In [16]:
import numpy as np

In [17]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [18]:
print(a[0])

[1 2 3 4]


In [19]:
a = np.zeros(6)
b = np.ones(6)
c = np.empty(6)

print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]


In [20]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [21]:
a = np.arange(0, 10, 2)
print(a)

[0 2 4 6 8]


In [30]:
arr = np.array([1,2,3,4,5,6,7,8])
arr = np.append(arr, [1,2])

arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [31]:
arr = np.delete(arr, 2)
arr

array([1, 2, 4, 5, 6, 7, 8, 1, 2])

In [32]:
arr = np.sort(arr)
arr

array([1, 1, 2, 2, 4, 5, 6, 7, 8])

In [33]:
arr_example = np.array([[[0,1,2,3],
                        [4,5,6,7]],
                       
                       [[0,1,2,3],
                       [4,5,6,7]],
                       
                       [[0,1,2,3],
                       [4,5,6,7]]])
print(arr_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [34]:
arr_example.ndim

3

In [35]:
arr_example.size

24

In [36]:
arr_example.shape

(3, 2, 4)

In [37]:
arr_one = np.array([[1,2,3,4,5]])

In [38]:
arr_one.ndim

2

In [39]:
arr_one.size

5

In [40]:
arr_one.shape

(1, 5)

## Reshape

In [43]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [46]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [48]:
b = a.reshape(6,1)
print(b)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


## Convert 1D to 2D

In [51]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [52]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [53]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [54]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [55]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [56]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [57]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Indexing and Slicing

In [58]:
data = np.array([1,2,3])
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [59]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [62]:
five_up = (a >= 5)
print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [63]:
div_by_2 = a[a%2==0]
print(div_by_2)

[ 2  4  6  8 10 12]


In [64]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

In [65]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [66]:
a_1 = np.array([[1,1],[2,2]])
a_2 = np.array([[3,3],[4,4]])

hasil = np.vstack((a_1, a_2))
print(hasil)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [67]:
hasil = np.hstack((a_1, a_2))
print(hasil)

[[1 1 3 3]
 [2 2 4 4]]
